// learn_vue/project1/dir1/components/todo/todo.vue
<template>
  <div>
    <input
      type="text"
      v-model='todo'
      @keyup.enter="add"
    >
    <ul>
      <li v-for='item in list'>{{item.text}} <button @click='del(item)'>X</button></li>
    </ul>
  </div>
</template>

<script>
import { reactive, toRefs } from "vue";
export default {
  setup() {
    const obj = reactive({
      todo: "",
      list: [{ id: Math.random(), text: "hello" }],
    });

    const add = () => {
      obj.list.unshift({
        id: Math.random(),
        text: obj.todo,
      });
      obj.todo = "";
    };
    const del = (item) => {
      obj.list = obj.list.filter((val) => val.id !== item.id);
    };
    return {
      ...toRefs(obj),
      add,
      del,
    };
  },
};
</script>

<style lang="less" scoped>
</style>

// learn_react/project1/src/day1/todo/index.jsx
import React, { useState } from 'react';
import ReactDOM from 'react-dom';

function App() {

  let [list, setList] = useState([{ id: Math.random(), text: "测试" }]);
  let [todo, setTodo] = useState('');
  const del = (item) => {
    let temp = list.filter(val => val.id != item.id)
    setList(temp)
  }
  const submit = () => {
    let temp = [...list]
    temp.unshift({ id: Math.random(), text: todo })
    setList(temp)
    setTodo('')
  }
  return <>
    <input
      type="text"
      value={todo}
      onChange={(e) => setTodo(e.target.value)}
      onKeyDown={(e) => { if (e.keyCode == 13) { submit() } }} />
    <ul>
      {
        list.map(item => {
          return <li key={item.id}>{item.text} <button onClick={() => { del(item) }}>X</button></li>
        })
      }
    </ul>
  </>
}

ReactDOM.render(<App />, document.getElementById('root'))
