// learn_vue/project1/src/components/todo/todo.vue
<template>
  <div>
    <input
      type="text"
      v-model='todo'
      @keyup.enter="add"
    >
    <ul>
      <li v-for='item in list'>{{item.text}} <button @click="del(item)">X</button></li>
    </ul>
  </div>
</template>
<script>
// @ is an alias to /src
export default {
  name: "XXX",
  data() {
    return {
      todo: "",
      list: [{ id: Math.random(), text: "hello" }],
    };
  },
  methods: {
    add() {
      this.list.unshift({
        id: Math.random(),
        text: this.todo,
      });
      this.todo = "";
    },
    del(item) {
      this.list = this.list.filter((val) => val.id != item.id);
    },
  },
};
</script>
<style lang="less">
</style>

// learn_react/project1/src/day1/todo/todo.jsx
import React, { useState } from 'react';
import ReactDOM from 'react-dom';
import Input from './input'
import List from './list'
function App() {
  let [list, setList] = useState([{ id: Math.random(), text: "测试" }]);
  let [todo, setTodo] = useState('');
  const del = (item) => {
    let temp = list.filter(val => val.id != item.id)
    setList(temp)
  }
  const submit = () => {
    let temp = [...list]
    temp.unshift({
      id: Math.random(),
      text: todo
    })
    // list.unshift({
    //   id: Math.random(),
    //   text: todo
    // })
    setList(temp)
    setTodo('')
  }
  return <>
    <Input
      value={todo}
      onChange={(e) => { setTodo(e.target.value) }}
      placeholder="hello"
      onKeyDown={(e) => {
        if (e.keyCode == 13) {
          submit()
        }
      }}
    />
    <List data={list} onDel={del} www={item => {
      return <h1>{item.text}</h1>
    }} />
  </>
}

ReactDOM.render(<App />, document.getElementById('root'))
